#!/bin/bash

# HOW TO USE
# ADD kubeplugin to plugins 

#sudo chmod +x ./kubeplugin
#sudo sudo cp -p ./kubeplugin /usr/bin/kubectl-kubeplugin
#kubectl kubeplugin top pods kube-system

# Define command-line arguments

RESOURCE_TYPE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl $1 $RESOURCE_TYPE -n $3 | tail -n +2 | while read line
do

 # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')


  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
echo $RESOURCE_TYPE $3 $NAME $CPU $MEMORY
done